const CATEGORIES_ACTION_TYPES = {
	// SET_CATEGORIES_MAP: "categories/SET_CATEGORIES_MAP",
	// SET_CATEGORIES: "categories/SET_CATEGORIES",
	FETCH_CATEGORIES_START: "category/FETH_CATEGORIES_START",
	FETCH_CATEGORIES_SUCCESS: "category/FETH_CATEGORIES_SUCCESS",
	FETCH_CATEGORIES_FAILED: "category/FETH_CATEGORIES_FAILED",
};

export default CATEGORIES_ACTION_TYPES;
